<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Finding\Enums;

class GallerySizeEnum
{
    const C_SMALL = 'Small';
    const C_MEDIUM = 'Medium';
    const C_LARGE = 'Large';
}
