<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class CompatibilitySpecificationCodeType
{
    const C_NAME_VALUE = 'NameValue';
    const C_AAIA = 'AAIA';
    const C_HSN = 'HSN';
    const C_CUSTOM_CODE = 'CustomCode';
}
