<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class DigitalDeliveryMethodCodeType
{
    const C_NONE = 'None';
    const C_DOWNLOADURL = 'DownloadURL';
    const C_ALTERNATE_DELIVERY_INSTRUCTIONS = 'AlternateDeliveryInstructions';
    const C_CUSTOM_CODE = 'CustomCode';
}
