<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class MachineTagTypeCodeType
{
    const C_SERVER_FLASH = 'ServerFlash';
    const C_SERVER_HTTP_COOKIE = 'ServerHttpCookie';
    const C_NO_TAG = 'NoTag';
    const C_CUSTOM_CODE = 'CustomCode';
}
