<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class PolicyComplianceStatusCodeType
{
    const C_GOOD = 'Good';
    const C_FAIR = 'Fair';
    const C_POOR = 'Poor';
    const C_FAILING = 'Failing';
    const C_CUSTOM_CODE = 'CustomCode';
}
