<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class RentalStatusCodeType
{
    const C_EXTENDED = 'Extended';
    const C_BUYOUT = 'Buyout';
    const C_RENTED = 'Rented';
    const C_COMPLETED = 'Completed';
    const C_CUSTOM_CODE = 'CustomCode';
}
