<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class SellingManagerPaidStatusCodeType
{
    const C_PAID = 'Paid';
    const C_PARTIALLY_PAID = 'PartiallyPaid';
    const C_UNPAID = 'Unpaid';
    const C_PENDING = 'Pending';
    const C_REFUNDED = 'Refunded';
    const C_CUSTOM_CODE = 'CustomCode';
}
