<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class TradingAssistantCodeType
{
    const C_NOTA_TRADING_ASSISTANT = 'NotATradingAssistant';
    const C_INACTIVE_TRADING_ASSISTANT = 'InactiveTradingAssistant';
    const C_BLOCKED_TRADING_ASSISTANT = 'BlockedTradingAssistant';
    const C_ACTIVE_TRADING_ASSISTANT = 'ActiveTradingAssistant';
    const C_ACTIVE_TRADING_POST = 'ActiveTradingPost';
    const C_CUSTOM_CODE = 'CustomCode';
}
