<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class WirelessCarrierIDCodeType
{
    const C_CINGULAR = 'Cingular';
    const C_T_MOBILE = 'TMobile';
    const C_SPRINT = 'Sprint';
    const C_NEXTEL = 'Nextel';
    const C_VERIZON = 'Verizon';
    const C_CINCINNATI_BELL = 'CincinnatiBell';
    const C_DOBSON = 'Dobson';
    const C_ALLTEL = 'Alltel';
    const C_LEAP = 'Leap';
    const C_US_CELLULAR = 'USCellular';
    const C_MOVISTAR = 'Movistar';
    const C_AMENA = 'Amena';
    const C_VODAFONE = 'Vodafone';
    const C_ATT = 'ATT';
    const C_CUSTOM_CODE = 'CustomCode';
}
