<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class SellingManagerAlertTypeCodeType
{
    const C_SOLD = 'Sold';
    const C_INVENTORY = 'Inventory';
    const C_AUTOMATION = 'Automation';
    const C_PAISA_PAY = 'PaisaPay';
    const C_GENERAL = 'General';
    const C_CUSTOM_CODE = 'CustomCode';
}
