<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class ShippingFeatureCodeType
{
    const C_DELIVERY_CONFIRMATION = 'DeliveryConfirmation';
    const C_SIGNATURE_CONFIRMATION = 'SignatureConfirmation';
    const C_STEALTH_POSTAGE = 'StealthPostage';
    const C_SATURDAY_DELIVERY = 'SaturdayDelivery';
    const C_OTHER = 'Other';
    const C_NOT_DEFINED = 'NotDefined';
    const C_CUSTOM_CODE = 'CustomCode';
}
