<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class ValueTypeCodeType
{
    const C_DECIMAL = 'Decimal';
    const C_NUMERIC = 'Numeric';
    const C_TEXT = 'Text';
    const C_ISBN = 'ISBN';
    const C_UPC = 'UPC';
    const C_EAN = 'EAN';
    const C_DATE = 'Date';
    const C_CODICE_FISCALE = 'CodiceFiscale';
    const C_DNI = 'DNI';
    const C_RUSSIAN_PASSPORT = 'RussianPassport';
    const C_CPF_TAXID = 'CPFTaxID';
    const C_TURKEYID = 'TurkeyID';
    const C_NIE = 'NIE';
    const C_NIF = 'NIF';
    const C_CEDULA = 'CEDULA';
    const C_NIT = 'NIT';
    const C_DRIVER_LICENSE = 'DriverLicense';
    const C_CNPJ = 'CNPJ';
    const C_CUSTOM_CODE = 'CustomCode';
}
