<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Types;

/**
 *
 * @property boolean $ExpressSellingPreference
 * @property boolean $ExpressApproved
 * @property boolean $GoodStanding
 * @property \DTS\eBaySDK\MerchantData\Types\FeedbackRequirementsType $FeedbackScore
 * @property \DTS\eBaySDK\MerchantData\Types\FeedbackRequirementsType $PositiveFeedbackPercent
 * @property \DTS\eBaySDK\MerchantData\Types\FeedbackRequirementsType $FeedbackAsSellerScore
 * @property \DTS\eBaySDK\MerchantData\Types\FeedbackRequirementsType $PositiveFeedbackAsSellerPercent
 * @property boolean $BusinessSeller
 * @property boolean $EligiblePayPalAccount
 * @property boolean $PayPalAccountAcceptsUnconfirmedAddress
 * @property boolean $CombinedPaymentsAccepted
 * @property boolean $FeedbackPublic
 */
class ExpressSellerRequirementsType extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'ExpressSellingPreference' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ExpressSellingPreference'
        ],
        'ExpressApproved' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'ExpressApproved'
        ],
        'GoodStanding' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'GoodStanding'
        ],
        'FeedbackScore' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\FeedbackRequirementsType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'FeedbackScore'
        ],
        'PositiveFeedbackPercent' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\FeedbackRequirementsType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PositiveFeedbackPercent'
        ],
        'FeedbackAsSellerScore' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\FeedbackRequirementsType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'FeedbackAsSellerScore'
        ],
        'PositiveFeedbackAsSellerPercent' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\FeedbackRequirementsType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PositiveFeedbackAsSellerPercent'
        ],
        'BusinessSeller' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'BusinessSeller'
        ],
        'EligiblePayPalAccount' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'EligiblePayPalAccount'
        ],
        'PayPalAccountAcceptsUnconfirmedAddress' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PayPalAccountAcceptsUnconfirmedAddress'
        ],
        'CombinedPaymentsAccepted' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'CombinedPaymentsAccepted'
        ],
        'FeedbackPublic' => [
            'type' => 'boolean',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'FeedbackPublic'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
