<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\BulkDataExchange\Enums;

class JobStatus
{
    const C_CREATED = 'Created';
    const C_SCHEDULED = 'Scheduled';
    const C_IN_PROCESS = 'InProcess';
    const C_COMPLETED = 'Completed';
    const C_ABORTED = 'Aborted';
    const C_FAILED = 'Failed';
}
